Bat-m/issue39
GRINN-dev/tacotac pull request #40
Opened 2023-02-21 16:24 UTC by Bat-m

2023-02-21 17:20 UTC, LouisLec requested changes
On reviendra bien sur sur les layouts, mais bon boulot ! Je te laisse faire les qqs modifs @Bat

2023-02-21 17:20 UTC, LouisLec commented on @tacotacIO/codegen/graphql/fragments/EventFragment.graphql
> +    ...EventBrandingFragment
on ne veut pas inclure les sous-types dans les fragments, sauf s'il s'agit d'une relation 1 to 1. On fait plutot ca au niveau de la query direct, genre:

```gql
query GetEventById($eventId: UUID!) {
  event(id: $eventId) {
    ...MyEvent
    attendees {
      nodes {
        ...MyAttendee
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      totalCount
    }
  }
}
```

2023-02-21 17:20 UTC, LouisLec commented on @tacotacIO/codegen/graphql/fragments/EventFragment.graphql
> +    ...EventBrandingFragment
comme ça, un fragment se limite exclusivcement à l'entité qu'il concerne. Deux avantages: on ne risque pas de fetcher trop d'infos si on veut juste les events et pas les attendees associés, et on sait mieux ou debugger/ajouter des champs quand necessaire

2023-02-21 17:20 UTC, LouisLec commented on apps/db/migrations/current/01000-events.sql
> +  long_text text,
pas besoin du champ long_text, il est equivalent à rich_text

2023-02-21 17:20 UTC, LouisLec commented on apps/db/migrations/current/01000-events.sql
> +    grant ALL  on table publ.event_brandings to :DATABASE_VISITOR;
no way ! ;)

2023-02-21 17:20 UTC, LouisLec commented on apps/db/migrations/current/01000-events.sql
> +$$ language plpgsql volatile set search_path to pg_catalog, public, pg_temp;
plutot que de fait un grant all, si le but était de permettre l'execution de cette fonction, mets-la plutot en security definer

2023-02-21 17:20 UTC, LouisLec commented on apps/db/migrations/current/01000-events.sql
> +create function publ.event_branding__insert_with_event() returns trigger as $$
mets-la plutot dans le schema priv, puisqu'on a pas besoin d'y accéder depuis l'exterieur de la BDD

2023-02-21 17:20 UTC, LouisLec commented on apps/site/components/table/Collection.tsx
> +  console.log("🚀 ~ file: Collection.tsx:47 ~ Collection ~ pathname:", pathname);
evitons de les laisser !

2023-02-22 09:51 UTC, Bat-m commented on apps/db/migrations/current/01000-events.sql
> +$$ language plpgsql volatile set search_path to pg_catalog, public, pg_temp;
ah en fait j'ai une erreur permission denied sur la table publ.event_brandings

2023-02-23 10:17 UTC, merged